export const tipsters: TopTipster[] = [
  {
    id: 1,
    initials: "MK",
    name: "Mwangi Kamau",
    tier: "ELITE",
    sports: "Football · EPL · UCL",
    accuracy: 94,
    subs: "2.4K",
    thisWeek: "+127",
    price: "KES 499/mo",
    free: false,
    avatarBg: "#6B21A8",
    borderColor: "#EAB308",
    accentColor: "#EAB308",
  },
  {
    id: 2,
    initials: "JO",
    name: "Janet Odhiambo",
    tier: "PRO",
    sports: "Basketball · NBA · BBL",
    accuracy: 89,
    subs: "1.8K",
    thisWeek: "+89",
    price: "KES 299/mo",
    free: false,
    avatarBg: "#065F46",
    borderColor: "#10B981",
    accentColor: "#10B981",
  },
  {
    id: 3,
    initials: "DM",
    name: "David Mutua",
    tier: "FREE",
    sports: "Football · FKF · AFCON",
    accuracy: 86,
    subs: "3.1K",
    thisWeek: "+203",
    price: null,
    free: true,
    avatarBg: "#7C3100",
    borderColor: "#10B981",
    accentColor: "#10B981",
  },
  {
    id: 4,
    initials: "AW",
    name: "Amina Wanjiku",
    tier: "PRO",
    sports: "Tennis · ATP · WTA",
    accuracy: 83,
    subs: "967",
    thisWeek: "+54",
    price: "KES 199/mo",
    free: false,
    avatarBg: "#0E4F6B",
    borderColor: "#10B981",
    accentColor: "#10B981",
  },
  {
    id: 5,
    initials: "BN",
    name: "Brian Njoroge",
    tier: "PRO",
    sports: "Rugby · Kenya Cup",
    accuracy: 81,
    subs: "744",
    thisWeek: "+41",
    price: "KES 249/mo",
    free: false,
    avatarBg: "#7C1D1D",
    borderColor: "#10B981",
    accentColor: "#10B981",
  },
];
 
export const followTipsters: FollowTipster[] = [
  { id: 6, initials: "SK", name: "Samuel Kiplagat", sports: "Football · La Liga · Pro Tier", accuracy: 88, subs: "1,240", avatarBg: "#7C3100", borderColor: "#EAB308" },
  { id: 7, initials: "FO", name: "Faith Otieno", sports: "Basketball · NBL · Free Tier", accuracy: 85, subs: "892", avatarBg: "#065F46", borderColor: "#10B981" },
  { id: 8, initials: "PM", name: "Peter Muthomi", sports: "Football · Serie A · Pro Tier", accuracy: 82, subs: "1,560", avatarBg: "#1e3a5f", borderColor: "#10B981" },
  { id: 9, initials: "GN", name: "Grace Ndung'u", sports: "Tennis · Grand Slams · Pro Tier", accuracy: 80, subs: "678", avatarBg: "#4a1942", borderColor: "#10B981" },
  { id: 10, initials: "RK", name: "Reuben Korir", sports: "Cricket · ICC · Free Tier", accuracy: 78, subs: "441", avatarBg: "#7C1D1D", borderColor: "#EAB308" },
  { id: 11, initials: "LW", name: "Lilian Waweru", sports: "Football · Bundesliga · Free Tier", accuracy: 77, subs: "1,020", avatarBg: "#065F46", borderColor: "#10B981" },
  { id: 12, initials: "CN", name: "Collins Ng'ang'a", sports: "Rugby · Super Rugby · Pro Tier", accuracy: 76, subs: "389", avatarBg: "#1e3a5f", borderColor: "#10B981" },
  { id: 13, initials: "IM", name: "Irene Mwangi", sports: "Football · FKF · Free Tier", accuracy: 75, subs: "2,140", avatarBg: "#7C3100", borderColor: "#10B981" },
];
 
export const tierStyles: Record<TierType, { bg: string; text: string }> = {
  ELITE: { bg: "bg-purple-800", text: "text-purple-200" },
  PRO: { bg: "bg-yellow-900/60", text: "text-yellow-400" },
  FREE: { bg: "bg-emerald-900/60", text: "text-emerald-300" },
};

export const SPORT_FILTERS: { label: SportFilter; icon: string | null }[] = [
  { label: "All", icon: null },
  { label: "Football", icon: "⚽" },
  { label: "Basketball", icon: "🏀" },
  { label: "Tennis", icon: "🎾" },
  { label: "Rugby", icon: "🏉" },
  { label: "Cricket", icon: "🏏" },
];

export const MOBILE_FILTERS = ["All Slips", "⚽ Football", "🏀 Basketball", "🔒 Free", "🔥 Hot"] as const;
 
export const ACCURACY_OPTIONS: AccuracyFilter[] = [
  "Any accuracy",
  "90%+ Elite",
  "80–90% Pro",
  "70–80% Standard",
];
 
export const PLATFORM_STYLES: Record<Platform, string> = {
  Sportpesa: "text-green-400 border-green-400/30 bg-green-400/10",
  Betin: "text-yellow-400 border-yellow-400/30 bg-yellow-400/10",
  "1xBet": "text-blue-400 border-blue-400/30 bg-blue-400/10",
  Betway: "text-purple-400 border-purple-400/30 bg-purple-400/10",
};
 
export const SPORT_ICON: Record<BetSlip["sport"], string> = {
  Football: "⚽",
  Basketball: "🏀",
  Tennis: "🎾",
  Rugby: "🏉",
  Cricket: "🏏",
};
 
export const BET_SLIPS: BetSlip[] = [
  {
    id: 1,
    initials: "MK",
    avatarBg: "#2d6a4f",
    name: "Mwangi Kamau",
    verified: true,
    sport: "Football",
    leagues: "EPL • UCL",
    odds: "14.70",
    type: "4-Leg Accumulator",
    timer: "02:13:50",
    timerUrgent: false,
    accuracy: 94,
    badge: "HOT PICK",
    badgeColor: "#f59e0b",
    selections: [
      { match: "Arsenal vs Man City", market: "Both Teams to Score", odd: "1.85", locked: false },
      { match: "Real Madrid vs Barca", market: "Over 2.5 Goals", odd: "1.72", locked: false },
      { locked: true },
      { locked: true },
    ],
    platforms: ["Sportpesa", "Betin", "1xBet"],
    price: "TZS 11,500",
    priceLabel: "one-time access",
    isFree: false,
  },
  {
    id: 2,
    initials: "DM",
    avatarBg: "#1e3a5f",
    name: "David Mutua",
    verified: true,
    sport: "Football",
    leagues: "FKF • AFCON",
    odds: "5.80",
    type: "3-Leg Accumulator",
    timer: "05:46:24",
    timerUrgent: false,
    accuracy: 86,
    badge: "FREE",
    badgeColor: "#8b5cf6",
    selections: [
      { match: "Gor Mahia vs Simba SC", market: "Home Win", odd: "2.10", locked: false },
      { match: "Yanga vs AFC Leopards", market: "Over 1.5 Goals", odd: "1.65", locked: false },
      { match: "Azam FC vs KCB FC", market: "BTTS", odd: "1.68", locked: false },
    ],
    platforms: ["Sportpesa", "Betway"],
    price: "FREE",
    priceLabel: "subscribers only",
    isFree: true,
  },
  {
    id: 3,
    initials: "JO",
    avatarBg: "#1a3a4a",
    name: "Janet Odhiambo",
    verified: true,
    sport: "Basketball",
    leagues: "NBA",
    odds: "8.40",
    type: "3-Leg Accumulator",
    timer: "00:57:56",
    timerUrgent: true,
    accuracy: 89,
    badge: "NEW",
    badgeColor: "#22c55e",
    selections: [
      { match: "Lakers vs Warriors", market: "Over 224.5 pts", odd: "1.90", locked: false },
      { locked: true },
      { locked: true },
    ],
    platforms: ["Betin", "1xBet", "Betway"],
    price: "TZS 6,900",
    priceLabel: "one-time access",
    isFree: false,
  },
  {
    id: 4,
    initials: "AW",
    avatarBg: "#4a1d3f",
    name: "Amina Wanjiku",
    verified: true,
    sport: "Tennis",
    leagues: "ATP • WTA",
    odds: "3.45",
    type: "2-Leg Accumulator",
    timer: "03:29:12",
    timerUrgent: false,
    accuracy: 83,
    selections: [
      { match: "Djokovic vs Alcaraz", market: "Djokovic Win", odd: "1.75", locked: false },
      { match: "Swiatek vs Osaka", market: "Over 22.5 Games", odd: "1.97", locked: false },
    ],
    platforms: ["Betway", "1xBet"],
    price: "TZS 4,500",
    priceLabel: "one-time access",
    isFree: false,
  },
  {
    id: 5,
    initials: "SK",
    avatarBg: "#3a2a10",
    name: "Samuel Kiplagat",
    verified: true,
    sport: "Football",
    leagues: "La Liga",
    odds: "22.50",
    type: "5-Leg Accumulator",
    timer: "04:29:12",
    timerUrgent: false,
    accuracy: 88,
    badge: "HOT PICK",
    badgeColor: "#f59e0b",
    selections: [
      { match: "Atletico vs Sevilla", market: "Home Win", odd: "1.80", locked: false },
      { match: "Valencia vs Villarreal", market: "BTTS", odd: "1.70", locked: false },
      { locked: true },
      { locked: true },
      { locked: true },
    ],
    platforms: ["Sportpesa", "Betin"],
    price: "TZS 9,000",
    priceLabel: "one-time access",
    isFree: false,
  },
  {
    id: 6,
    initials: "PM",
    avatarBg: "#1a2a4a",
    name: "Peter Muthomi",
    verified: true,
    sport: "Football",
    leagues: "Serie A",
    odds: "6.15",
    type: "3-Leg Accumulator",
    timer: "01:53:12",
    timerUrgent: true,
    accuracy: 82,
    selections: [
      { match: "Juventus vs Milan", market: "Draw", odd: "3.20", locked: false },
      { match: "Napoli vs Roma", market: "Over 2.5 Goals", odd: "1.92", locked: false },
      { locked: true },
    ],
    platforms: ["Betin", "Betway"],
    price: "TZS 5,500",
    priceLabel: "one-time access",
    isFree: false,
  },
];